variables:
  DOCKER_HOST: tcp://docker:2375/
  QUANTUM_CLI: registry.internal.planetary-networks.de/quantum-public/cli:2
  QUANTUM_ENDPOINT: sva
  DOCKER_AUTH_CONFIG: '{ "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_AUTH" } }}'

stages:
  - build
  - build_release
  - deploy_release

services:
  - docker:19.03.0-dind

before_script:
  - docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker_build:
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    DOCKERFILE: Dockerfile
  allow_failure: false
  script:
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest --tag $IMAGE:$CI_COMMIT_SHA --tag $IMAGE:latest -f $DOCKERFILE .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest
  only:
    - releases

.docker_build_release:
  stage: build_release
  image:
    name: docker/compose:1.25.0
    entrypoint: ["/bin/sh", "-c"]
  cache:
    key: "${CI_PIPELINE_ID}-${PROJECT}"
    paths: [quantum.yml]
  script:
    - sed "s/%PROJECT%/${PROJECT}/g" < stack.yml.template > stack.yml
    - docker-compose -f docker-compose.yml -f stack.yml config > quantum.yml
  tags: [v2]
  allow_failure: false
  when: manual
  only:
    - releases

.deploy_release:
  stage: deploy_release
  needs: ["docker-build"]
  image: $QUANTUM_CLI
  cache:
    key: "${CI_PIPELINE_ID}-${PROJECT}"
    paths: [quantum.yml]
  script:
    - quantum-cli stack update --create --stack $PROJECT-rss_importer-$QUANTUM_ENDPOINT --wait
  tags: [v2]
  allow_failure: false
  when: on_success
  only:
    - releases

# List of Releases:
#
# bb-eberswalde
# bb-havelland
# bb-hohen_neuendorf
# bb-frankfurt
# bb-ruedersdorf
# bb-schoenefeld
# bb-seelow
# bb-uckermark
#

#
# List of releases to build
#
bb-eberswalde-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-eberswalde
    NODENAME: node-002.sva
bb-frankfurt-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-frankfurt
    NODENAME: node-002.sva
bb-havelland-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-havelland
    NODENAME: node-002.sva
bb-hohen-neuendorf-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-hohen-neuendorf
    NODENAME: node-002.sva
bb-ruedersdorf-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-ruedersdorf
    NODENAME: node-002.sva
bb-schoenefeld-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-schoenefeld
    NODENAME: node-002.sva
bb-seelow-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-seelow
    NODENAME: node-002.sva
bb-uckermark-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-uckermark
    NODENAME: node-002.sva

#
# List of releases to deploy
#
bb-eberswalde-deploy:
  extends: .deploy_release
  needs: ["bb-eberswalde-build"]
  variables:
    PROJECT: bb-eberswalde
    QUANTUM_ENDPOINT: sva
bb-frankfurt-deploy:
  extends: .deploy_release
  needs: ["bb-frankfurt-build"]
  variables:
    PROJECT: bb-frankfurt
    QUANTUM_ENDPOINT: sva
bb-havelland-deploy:
  extends: .deploy_release
  needs: ["bb-havelland-build"]
  variables:
    PROJECT: bb-havelland
    QUANTUM_ENDPOINT: sva
bb-hohen-neuendorf-deploy:
  extends: .deploy_release
  needs: ["bb-hohen-neuendorf-build"]
  variables:
    PROJECT: bb-hohen-neuendorf
    QUANTUM_ENDPOINT: sva
bb-ruedersdorf-deploy:
  extends: .deploy_release
  needs: ["bb-ruedersdorf-build"]
  variables:
    PROJECT: bb-ruedersdorf
    QUANTUM_ENDPOINT: sva
bb-schoenefeld-deploy:
  extends: .deploy_release
  needs: ["bb-schoenefeld-build"]
  variables:
    PROJECT: bb-schoenefeld
    QUANTUM_ENDPOINT: sva
bb-seelow-deploy:
  extends: .deploy_release
  needs: ["bb-seelow-build"]
  variables:
    PROJECT: bb-seelow
    QUANTUM_ENDPOINT: sva
bb-uckermark-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-uckermark
    NODENAME: node-002.sva
