variables:
  DOCKER_HOST: tcp://docker:2375/
  QUANTUM_CLI: registry.internal.planetary-networks.de/quantum-public/cli:2
  QUANTUM_ENDPOINT: sva
  DOCKER_AUTH_CONFIG: '{ "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_AUTH" } }}'

stages:
  - build
  - build_release
  - deploy_release

services:
  - docker:19.03.0-dind

before_script:
  - docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker_build:
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    DOCKERFILE: Dockerfile
  allow_failure: false
  script:
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest --tag $IMAGE:$CI_COMMIT_SHA --tag $IMAGE:latest -f $DOCKERFILE .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest
  only:
    - master

.docker_build_release:
  stage: build_release
  image:
    name: docker/compose:1.25.0
    entrypoint: ["/bin/sh", "-c"]
  cache:
    key: "${CI_PIPELINE_ID}-${PROJECT}"
    paths: [quantum.yml]
  script:
    - sed "s/%PROJECT%/${PROJECT}/g" < stack.yml.template > stack.yml
    - docker-compose -f docker-compose.yml -f stack.yml config > quantum.yml
  tags: [v2]
  allow_failure: false
  when: on_success
  only:
    - master

.deploy_release:
  stage: deploy_release
  needs: ["docker-build"]
  image: $QUANTUM_CLI
  cache:
    key: "${CI_PIPELINE_ID}-${PROJECT}"
    paths: [quantum.yml]
  script:
    - quantum-cli stack update --create --stack $PROJECT-rss_importer-$QUANTUM_ENDPOINT --wait
  tags: [v2]
  allow_failure: false
  when: on_success
  only:
    - master

# List of Releases:
#
# bb-amt-schlieben
# bb-angermuende
# bb-bad-belzig
# bb-birkenwerder
# bb-eberswalde
# bb-eisenhuettenstadt
# bb-falkenberg-elster
# bb-frankfurt
# bb-gransee
# bb-havelland
# bb-herzberg-elster
# bb-hohen-neuendorf
# bb-kyritz
# bb-michendorf
# bb-ruedersdorf
# bb-schoenefeld
# bb-seelow
# bb-uckermark
# bb-bernau
# bb-nuthetal
#
# mv-hagenow
#

#
# List of releases to build
#
bb-amt-schlieben-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-amt-schlieben
    NODENAME: node-002.sva
bb-angermuende-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-angermuende
    NODENAME: node-002.sva
bb-bad-belzig-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-bad-belzig
    NODENAME: node-002.sva
bb-birkenwerder-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-birkenwerder
    NODENAME: node-002.sva
bb-eberswalde-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-eberswalde
    NODENAME: node-002.sva
bb-eisenhuettenstadt-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-eisenhuettenstadt
    NODENAME: node-002.sva
bb-falkenberg-elster-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-falkenberg-elster
    NODENAME: node-002.sva
bb-frankfurt-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-frankfurt
    NODENAME: node-002.sva
bb-gransee-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-gransee
    NODENAME: node-002.sva
bb-havelland-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-havelland
    NODENAME: node-002.sva
bb-herzberg-elster-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-herzberg-elster
    NODENAME: node-002.sva
bb-hohen-neuendorf-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-hohen-neuendorf
    NODENAME: node-002.sva
bb-kyritz-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-kyritz
    NODENAME: node-002.sva
bb-michendorf-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-michendorf
    NODENAME: node-002.sva
bb-ruedersdorf-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-ruedersdorf
    NODENAME: node-002.sva
bb-schoenefeld-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-schoenefeld
    NODENAME: node-002.sva
bb-seelow-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-seelow
    NODENAME: node-002.sva
bb-uckermark-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-uckermark
    NODENAME: node-002.sva
bb-bernau-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-bernau
    NODENAME: node-002.sva   
bb-nuthetal-build:
  extends: .docker_build_release
  variables:
    PROJECT: bb-nuthetal
    NODENAME: node-002.sva    
mv-hagenow-build:
  extends: .docker_build_release
  variables:
    PROJECT: mv-hagenow
    NODENAME: node-002.sva

#
# List of releases to deploy
#
bb-amt-schlieben-deploy:
  extends: .deploy_release
  needs: ["bb-amt-schlieben-build"]
  variables:
    PROJECT: bb-amt-schlieben
    QUANTUM_ENDPOINT: sva
bb-angermuende-deploy:
  extends: .deploy_release
  needs: ["bb-angermuende-build"]
  variables:
    PROJECT: bb-angermuende
    QUANTUM_ENDPOINT: sva
bb-bad-belzig-deploy:
  extends: .deploy_release
  needs: ["bb-bad-belzig-build"]
  variables:
    PROJECT: bb-bad-belzig
    QUANTUM_ENDPOINT: sva
bb-birkenwerder-deploy:
  extends: .deploy_release
  needs: ["bb-birkenwerder-build"]
  variables:
    PROJECT: bb-birkenwerder
    QUANTUM_ENDPOINT: sva
bb-eberswalde-deploy:
  extends: .deploy_release
  needs: ["bb-eberswalde-build"]
  variables:
    PROJECT: bb-eberswalde
    QUANTUM_ENDPOINT: sva
bb-eisenhuettenstadt-deploy:
  extends: .deploy_release
  needs: ["bb-eisenhuettenstadt-build"]
  variables:
    PROJECT: bb-eisenhuettenstadt
    QUANTUM_ENDPOINT: sva
bb-falkenberg-elster-deploy:
  extends: .deploy_release
  needs: ["bb-falkenberg-elster-build"]
  variables:
    PROJECT: bb-falkenberg-elster
    QUANTUM_ENDPOINT: sva
bb-frankfurt-deploy:
  extends: .deploy_release
  needs: ["bb-frankfurt-build"]
  variables:
    PROJECT: bb-frankfurt
    QUANTUM_ENDPOINT: sva
bb-gransee-deploy:
  extends: .deploy_release
  needs: ["bb-gransee-build"]
  variables:
    PROJECT: bb-gransee
    QUANTUM_ENDPOINT: sva
bb-havelland-deploy:
  extends: .deploy_release
  needs: ["bb-havelland-build"]
  variables:
    PROJECT: bb-havelland
    QUANTUM_ENDPOINT: sva
bb-herzberg-elster-deploy:
  extends: .deploy_release
  needs: ["bb-herzberg-elster-build"]
  variables:
    PROJECT: bb-herzberg-elster
    QUANTUM_ENDPOINT: sva
bb-hohen-neuendorf-deploy:
  extends: .deploy_release
  needs: ["bb-hohen-neuendorf-build"]
  variables:
    PROJECT: bb-hohen-neuendorf
    QUANTUM_ENDPOINT: sva
bb-kyritz-deploy:
  extends: .deploy_release
  needs: ["bb-kyritz-build"]
  variables:
    PROJECT: bb-kyritz
    QUANTUM_ENDPOINT: sva
bb-michendorf-deploy:
  extends: .deploy_release
  needs: ["bb-michendorf-build"]
  variables:
    PROJECT: bb-michendorf
    QUANTUM_ENDPOINT: sva
bb-ruedersdorf-deploy:
  extends: .deploy_release
  needs: ["bb-ruedersdorf-build"]
  variables:
    PROJECT: bb-ruedersdorf
    QUANTUM_ENDPOINT: sva
bb-schoenefeld-deploy:
  extends: .deploy_release
  needs: ["bb-schoenefeld-build"]
  variables:
    PROJECT: bb-schoenefeld
    QUANTUM_ENDPOINT: sva
bb-seelow-deploy:
  extends: .deploy_release
  needs: ["bb-seelow-build"]
  variables:
    PROJECT: bb-seelow
    QUANTUM_ENDPOINT: sva
bb-uckermark-deploy:
  extends: .deploy_release
  needs: ["bb-uckermark-build"]
  variables:
    PROJECT: bb-uckermark
    QUANTUM_ENDPOINT: sva
bb-bernau-deploy:
  extends: .deploy_release
  needs: ["bb-bernau-build"]
  variables:
    PROJECT: bb-bernau
    QUANTUM_ENDPOINT: sva
bb-nuthetal-deploy:
  extends: .deploy_release
  needs: ["bb-nuthetal-build"]
  variables:
    PROJECT: bb-nuthetal
    QUANTUM_ENDPOINT: sva        
mv-hagenow-deploy:
  extends: .deploy_release
  needs: ["mv-hagenow-build"]
  variables:
    PROJECT: mv-hagenow
    QUANTUM_ENDPOINT: sva
