version: '3.7'

services:
  db:
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro

  cron:
    build:
      context: .
    volumes:
      - ./docker/database.yml:/app/config/database.yml
      - .:/app
