version: '3.7'

services:
  db:
    image: 'postgres:10.3-alpine'
    environment:
      POSTGRES_USER: smart
      POSTGRES_PASSWORT: smart
      POSTGRES_DB: smart
    networks:
      public:
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  cron:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-rss-importer
    environment:
      DB_HOST: smart-village-app-${PROJECT}-rss-importer
      RAILS_ENV: production
      SVA_COMMUNITY: ${PROJECT}
      RAILS_LOG_TO_STDOUT: 1
    entrypoint: sh
    command: bin/start-cron.sh
    depends_on: [db]
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
      - source: mainserver-common-master-key
        target: /app/config/credentials/production.key
    volumes:
      - settings:/app/config/settings

volumes:
  db:
  unicorn:
  assets:
  settings:

configs:
  unicorn-5-worker:
    external: true
  mainserver-common-master-key:
    external: true

networks:
  public:
    external: true
