version: '3.7'

services:
  cron:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-rss-importer/FOOBAR-rss_importer
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - public
      - logs
      - smart-village-app-FOOBAR-rss-importer
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure

  db:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      smart-village-app-FOOBAR-rss-importer:
        aliases:
          - smart-village-app-FOOBAR-rss-importer
      adminer:
        aliases:
          - json-2-graphql-converter

networks:
  smart-village-app-FOOBAR-rss-importer:
    external: true
  adminer:
    external: true
  logs:
    external: true
  public:
    external: true
