version: '3.7'

services:
  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-rss-importer/bb-frankfurt-rss_importer
    networks:
      - default
      - public
      - logs
      - smart-village-app-bb-frankfurt-rss-importer
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.redirect.entryPoint: https
        traefik.frontend.rule: Host:rss-importer.bb-frankfurt.smart-village.app
        traefik.port: '80'
      restart_policy:
        condition: on-failure

  cron:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-rss-importer/bb-frankfurt-rss_importer
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - public
      - logs
      - smart-village-app-bb-frankfurt-rss-importer
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1

  db:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      smart-village-app-bb-frankfurt-rss-importer:
        aliases:
          - smart-village-app-bb-frankfurt-rss-importer
      adminer:
        aliases:
          - json-2-graphql-converter

networks:
  smart-village-app-bb-frankfurt-rss-importer:
    external: true
  adminer:
    external: true
  logs:
    external: true
  public:
    external: true
