# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 2368cd20f2fc12ca469fa06ef8a16d462eef81c98465a12456bba0c864e7bea5a375ec67f50cb8ae9ac90fa619c91d9095cea9e4e57f8af6667c252316bfac7c

auth_server:
  url: "https://server.bb-frankfurt.smart-village.app"
  callback_url: "https://rss-importer.bb-frankfurt.smart-village.app/oauth/confirm_access"

target_server:
  url: "https://json.bb-frankfurt.smart-village.app/api"
  __comment: "re-use credetials from auth_server"
# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.

rss_feeds:
  - url: http://smart-village.net/
    import:
      intro: false
      body: "encoded"
      external_id: false
      title: "title"
      images: false
    auth:
      key: "Cl_3D00D89xTrjFVJiSfA0sLayndpqQKi8UQq9yYxE8"
      secret: "t5cSuQ8gN1Ggv8v96D8x7GpNv8Q33dKdZkZy4FIj9Rw"
