bb_amt_schlieben:
  oauth_server: "https://server.bb-amt-schlieben.smart-village.app"
  target_server: "https://json.bb-amt-schlieben.smart-village.app/api"
  dashboard_project_id: "9o4zqzklxdmcy285nyltlazrido44bsy2udzx37j02r4wmdz"

bb_bad_belzig:
  oauth_server: "https://server.bad-belzig.smart-village.app"
  target_server: "https://json.bb-bad-belzig.smart-village.app/api"
  dashboard_project_id: "6os4gwyn3gy1x1hogiyodzeflhtsvrc1n9srobtxo4527deh"

bb_birkenwerder:
  oauth_server: "https://server.bb-birkenwerder.smart-village.app"
  target_server: "https://json.bb-birkenwerder.smart-village.app/api"
  dashboard_project_id: "x1lmnim8mcfpdq02mncx0qibistoe9s78vu9jby4axh89lrl"

bb_eberswalde:
  oauth_server: "https://server.bb-eberswalde.smart-village.app"
  target_server: "https://json.bb-eberswalde.smart-village.app/api"
  dashboard_project_id: "t79y544dnqlxhco985nhojayyk2a8ggx47ymqxvxp1294mhs"

bb_eisenhuettenstadt:
  oauth_server: "https://server.eisenhuettenstadt.smart-village.app"
  target_server: "https://json.bb-eisenhuettenstadt.smart-village.app/api"
  dashboard_project_id: "govby43soiz8o439d4sz1ijzm6z4y7u9sb2q38dvuvao06ag"

bb_falkenberg_elster:
  oauth_server: "https://server.bb-falkenberg-elster.smart-village.app"
  target_server: "https://json.bb-falkenberg-elster.smart-village.app/api"
  dashboard_project_id: "vy44tnj43il089u810vz75ij04ptcfll558wie8xywg0k8in"

bb_frankfurt:
  oauth_server: "https://server.bb-frankfurt.smart-village.app"
  target_server: "https://json.bb-frankfurt.smart-village.app/api"
  dashboard_project_id: "oimlg8hxf990ufbvp159l3gklkmb7d8nhqy1h2acjuczzl4x"

bb_gransee:
  oauth_server: "https://server.bb-gransee.smart-village.app"
  target_server: "https://json.bb-gransee.smart-village.app/api"
  dashboard_project_id: "xb57arpqzw8gcbssl9khs1jdptnfiq9m0rusqlrki7akup6e"

bb_havelland:
  oauth_server: "https://server.bb-havelland.smart-village.app"
  target_server: "https://json.bb-havelland.smart-village.app/api"
  dashboard_project_id: "1w2tt902egvu0e5nq8jwi5gzberihpsrjkuri8xcfx1vnx6u"

bb_herzberg_elster:
  oauth_server: "https://server.bb-herzberg-elster.smart-village.app"
  target_server: "https://json.bb-herzberg-elster.smart-village.app/api"
  dashboard_project_id: "w3bp7vjjl3o8r4guyigak7m5ok1bccbc3i59wa86yevn9s8m"

bb_hohen_neuendorf:
  oauth_server: "https://server.bb-hohen-neuendorf.smart-village.app"
  target_server: "https://json.bb-hohen-neuendorf.smart-village.app/api"
  dashboard_project_id: "g4f9em34rsxxpj8axxozpc6441t989s5m15plnk5rp8whd82"

bb_kyritz:
  oauth_server: "https://server.bb-kyritz.smart-village.app"
  target_server: "https://json.bb-kyritz.smart-village.app/api"
  dashboard_project_id: "oexdkmzdc0ia8b9syh0702sdf9nksp81v44lhekplc1l77u5"

bb_ruedersdorf:
  oauth_server: "https://server.bb-ruedersdorf.smart-village.app"
  target_server: "https://json.bb-ruedersdorf.smart-village.app/api"
  dashboard_project_id: "tb5jou75x05umuerik1uat7xrtr5qg51g05h2q7he8pxcpdl"

bb_seelow:
  oauth_server: "https://server.bb-seelow.smart-village.app"
  target_server: "https://json.bb-seelow.smart-village.app/api"
  dashboard_project_id: "hn5gja1vsbfaf7e9d5bzlknqjwqrfaer5sou0ti4ea5mk9j8"

bb_schoenefeld:
  oauth_server: "https://server.bb-schoenefeld.smart-village.app"
  target_server: "https://json.bb-schoenefeld.smart-village.app/api"
  dashboard_project_id: "eruvz76rx8h3hogs5ogc6jgl9bvtzun789pioj4iocapetd4"

bb_uckermark:
  oauth_server: "https://server.bb-uckermark.smart-village.app"
  target_server: "https://json.bb-uckermark.smart-village.app/api"
  dashboard_project_id: "n5ck8fphaw4c2ddyoz1oswvtmmtyfcg01e8xtb3ftbjf6b6u"

local_localhost:
  oauth_server: "http://localhost:4000"
  target_server: "http://localhost:5000/api"
  dashboard_project_id: "randomrandomrandomrandomrandomrandomrandomrandom"
